name: helm-release

on:
  push:
    branches:
      - main
      - "mimir-distributed-release-[0-9]+.[0-9]+"

jobs:
  call-update-helm-repo:
    uses: grafana/helm-charts/.github/workflows/update-helm-repo.yaml@update-helm-repo-fix-deps
    with:
      charts_dir: operations/helm/charts
      cr_configfile: operations/helm/cr.yaml
      ct_configfile: operations/helm/ct.yaml
    secrets:
      helm_repo_token: ${{ secrets.GITHUB_TOKEN }}
      github_app_id: ${{ secrets.MIMIR_HELM_RELEASE_APP_ID }}
      github_app_pem: ${{ secrets.MIMIR_HELM_RELEASE_APP_KEY_PEM }}
